spring:
  application:
    name: appointment-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  servlet:
    multipart:
      max-file-size: 4096KB
      max-request-size: 8192KB

cloudinary:
  cloud-name: 
  api-key: 
  api-secret: 

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}
