spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}

#langchain4j:
#  google-ai-gemini:
#    chat-model:
#      api-key: ${GOOGLE_AI_GEMINI_API_KEY}
#      model-name: ${GOOGLE_AI_GEMINI_MODEL_NAME:gemini-2.0-flash}
#      log-requests-and-responses: true
#      temperature: 1.0
#      top-p: 0.8
#      top-k: 64
#      max-output-tokens: 8192
