server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-facing-service
          uri: lb://patient-facing-service
          predicates:
            - Path=/api/v1/patients/**
        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/api/v1/staff/**
        - id: medical-record-service
          uri: lb://medical-record-service
          predicates:
            - Path=/api/v1/medical-records/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**,/api/v1/timeslots/**,/api/v1/doctor-timeslots/**,/api/v1/files
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: ${CORS_ALLOWED_ORIGINS}
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
