spring:
  application:
    name: staff-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:youremail@gmail.com}
    password: ${MAIL_PASSWORD:yourapppassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}

# Swagger / OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  show-actuator: false
  # Only expose Staff Service controllers
  packages-to-scan: com.example.hms.staffservice.staffmanagement.controller
