spring:
  application:
    name: staff-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}
